import { IProject } from '../interfaces/project.interface';

export const PROJECTS: IProject[] = [
  {
    id: 1,
    name: 'Kariba redd+ -Zimbabwe',
    image: '/assets/Tile_Image.jpg',
    title: 'Reduced Emissions from Deforestation and Degradation',
    offset: 957842,
    description: 'Protects forests and wildlife on the southern shores of Lake Kariba in Zimbabwe, forming a giant biodiversity corridor.',
    price: 7.50,
  },
  {
    id: 2,
    name: 'Arcata synnybrae tract - USA',
    image: '/assets/Tile_Image.jpg',
    title: 'Improved Forest Management',
    offset: 710093,
    description: 'Preservation of large tracts of coastal Redwood and Douglas fir that were slated for harvesting by the timber company.',
  },
  {
    id: 3,
    name: 'Kariba redd+ -Zimbabwe',
    image: '/assets/Tile_Image.jpg',
    title: 'Reduced Emissions from Deforestation and Degradation',
    offset: 957842,
    description: 'Protects forests and wildlife on the southern shores of Lake Kariba in Zimbabwe, forming a giant biodiversity corridor.',
    price: 7.50,
  },
  {
    id: 4,
    name: 'Arcata synnybrae tract - USA',
    image: '/assets/Tile_Image.jpg',
    title: 'Improved Forest Management',
    offset: 710093,
    description: 'Preservation of large tracts of coastal Redwood and Douglas fir that were slated for harvesting by the timber company.',
  },
  {
    id: 5,
    name: 'Kariba redd+ -Zimbabwe',
    image: '/assets/Tile_Image.jpg',
    title: 'Reduced Emissions from Deforestation and Degradation',
    offset: 957842,
    description: 'Protects forests and wildlife on the southern shores of Lake Kariba in Zimbabwe, forming a giant biodiversity corridor.',
    price: 7.50,
  },
  {
    id: 6,
    name: 'Arcata synnybrae tract - USA',
    image: '/assets/Tile_Image.jpg',
    title: 'Improved Forest Management',
    offset: 710093,
    description: 'Preservation of large tracts of coastal Redwood and Douglas fir that were slated for harvesting by the timber company.',
  },
  {
    id: 7,
    name: 'Kariba redd+ -Zimbabwe',
    image: '/assets/Tile_Image.jpg',
    title: 'Reduced Emissions from Deforestation and Degradation',
    offset: 957842,
    description: 'Protects forests and wildlife on the southern shores of Lake Kariba in Zimbabwe, forming a giant biodiversity corridor.',
    price: 7.50,
  },
  {
    id: 8,
    name: 'Arcata synnybrae tract - USA',
    image: '/assets/Tile_Image.jpg',
    title: 'Improved Forest Management',
    offset: 710093,
    description: 'Preservation of large tracts of coastal Redwood and Douglas fir that were slated for harvesting by the timber company.',
  },
];
